name: Generate Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: pip install sphinx
    - run: sphnix-quickstart -q -p CSC510 Group 30 Homework -a Swarangi Gaurkar -v 1
