name: Generate Documentation Setup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: pip install sphinx
    - run: sphinx-quickstart -q -p CSC510_Group_30_Homework -a Swarangi -v 1
    - name: Push changes
      run: git add --no-all
