name: Generate Documentation Setup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: pip install sphinx
    - run: sphinx-quickstart -q -p CSC510_Group_30_Homework -a Swarangi Gaurkar -v 1
