name: Code Coverage

on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - run: pip install -U sphinx
            - run: chmod u=a /Documentation
            - run: sphinx-build -b html . /Documentation
            - run: git add -A
